package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * Artists generated by hbm2java
 */
public class Artists implements java.io.Serializable {

	private Integer artistId;
	private Integer height;
	private String name;
	private String nameEg;
	private String weight;
	private String langrange;
	private String start;
	private String livePet;
	private String bloodType;
	private String loveToSay;
	private String job;
	private String company;
	private String bestHobby;
	private String worstBobby;
	private String birthDate;
	private String bestWish;
	private String hobby;
	private String likeColor;
	private String likedrink;

	public Artists() {
	}

	public Artists(Integer height, String name, String nameEg, String weight, String langrange, String start,
			String livePet, String bloodType, String loveToSay, String job, String company, String bestHobby,
			String worstBobby, String birthDate, String bestWish, String hobby, String likeColor, String likedrink) {
		this.height = height;
		this.name = name;
		this.nameEg = nameEg;
		this.weight = weight;
		this.langrange = langrange;
		this.start = start;
		this.livePet = livePet;
		this.bloodType = bloodType;
		this.loveToSay = loveToSay;
		this.job = job;
		this.company = company;
		this.bestHobby = bestHobby;
		this.worstBobby = worstBobby;
		this.birthDate = birthDate;
		this.bestWish = bestWish;
		this.hobby = hobby;
		this.likeColor = likeColor;
		this.likedrink = likedrink;
	}

	public Integer getArtistId() {
		return this.artistId;
	}

	public void setArtistId(Integer artistId) {
		this.artistId = artistId;
	}

	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNameEg() {
		return this.nameEg;
	}

	public void setNameEg(String nameEg) {
		this.nameEg = nameEg;
	}

	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public String getLangrange() {
		return this.langrange;
	}

	public void setLangrange(String langrange) {
		this.langrange = langrange;
	}

	public String getStart() {
		return this.start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getLivePet() {
		return this.livePet;
	}

	public void setLivePet(String livePet) {
		this.livePet = livePet;
	}

	public String getBloodType() {
		return this.bloodType;
	}

	public void setBloodType(String bloodType) {
		this.bloodType = bloodType;
	}

	public String getLoveToSay() {
		return this.loveToSay;
	}

	public void setLoveToSay(String loveToSay) {
		this.loveToSay = loveToSay;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getBestHobby() {
		return this.bestHobby;
	}

	public void setBestHobby(String bestHobby) {
		this.bestHobby = bestHobby;
	}

	public String getWorstBobby() {
		return this.worstBobby;
	}

	public void setWorstBobby(String worstBobby) {
		this.worstBobby = worstBobby;
	}

	public String getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(String birthDate) {
		this.birthDate = birthDate;
	}

	public String getBestWish() {
		return this.bestWish;
	}

	public void setBestWish(String bestWish) {
		this.bestWish = bestWish;
	}

	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	public String getLikeColor() {
		return this.likeColor;
	}

	public void setLikeColor(String likeColor) {
		this.likeColor = likeColor;
	}

	public String getLikedrink() {
		return this.likedrink;
	}

	public void setLikedrink(String likedrink) {
		this.likedrink = likedrink;
	}

}
