package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * CountStatis generated by hbm2java
 */
public class CountStatis implements java.io.Serializable {

	private CountStatisId id;

	public CountStatis() {
	}

	public CountStatis(CountStatisId id) {
		this.id = id;
	}

	public CountStatisId getId() {
		return this.id;
	}

	public void setId(CountStatisId id) {
		this.id = id;
	}

}
