package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * EuserDetail generated by hbm2java
 */
public class EuserDetail implements java.io.Serializable {

	private Integer idUserDetail;
	private Euser euser;
	private String qqNo;
	private String imei;
	private String cellPhoneNo;
	private Integer contact;
	private Integer location;
	private Integer gender;

	public EuserDetail() {
	}

	public EuserDetail(Euser euser, String qqNo, String imei, String cellPhoneNo, Integer contact, Integer location,
			Integer gender) {
		this.euser = euser;
		this.qqNo = qqNo;
		this.imei = imei;
		this.cellPhoneNo = cellPhoneNo;
		this.contact = contact;
		this.location = location;
		this.gender = gender;
	}

	public Integer getIdUserDetail() {
		return this.idUserDetail;
	}

	public void setIdUserDetail(Integer idUserDetail) {
		this.idUserDetail = idUserDetail;
	}

	public Euser getEuser() {
		return this.euser;
	}

	public void setEuser(Euser euser) {
		this.euser = euser;
	}

	public String getQqNo() {
		return this.qqNo;
	}

	public void setQqNo(String qqNo) {
		this.qqNo = qqNo;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getCellPhoneNo() {
		return this.cellPhoneNo;
	}

	public void setCellPhoneNo(String cellPhoneNo) {
		this.cellPhoneNo = cellPhoneNo;
	}

	public Integer getContact() {
		return this.contact;
	}

	public void setContact(Integer contact) {
		this.contact = contact;
	}

	public Integer getLocation() {
		return this.location;
	}

	public void setLocation(Integer location) {
		this.location = location;
	}

	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

}
