package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * FriendListUser generated by hbm2java
 */
public class FriendListUser implements java.io.Serializable {

	private Integer idfriendListUser;
	private Euser euser;
	private FriendList friendList;
	private String backName;
	private Integer friendListId;

	public FriendListUser() {
	}

	public FriendListUser(Euser euser, FriendList friendList, String backName, Integer friendListId) {
		this.euser = euser;
		this.friendList = friendList;
		this.backName = backName;
		this.friendListId = friendListId;
	}

	public Integer getIdfriendListUser() {
		return this.idfriendListUser;
	}

	public void setIdfriendListUser(Integer idfriendListUser) {
		this.idfriendListUser = idfriendListUser;
	}

	public Euser getEuser() {
		return this.euser;
	}

	public void setEuser(Euser euser) {
		this.euser = euser;
	}

	public FriendList getFriendList() {
		return this.friendList;
	}

	public void setFriendList(FriendList friendList) {
		this.friendList = friendList;
	}

	public String getBackName() {
		return this.backName;
	}

	public void setBackName(String backName) {
		this.backName = backName;
	}

	public Integer getFriendListId() {
		return this.friendListId;
	}

	public void setFriendListId(Integer friendListId) {
		this.friendListId = friendListId;
	}

}
