package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * Images generated by hbm2java
 */
public class Images implements java.io.Serializable {

	private Integer imageId;
	private Euser euser;
	private Locations locations;
	private String imageSrc;
	private Integer imageOwner;
	private String demo;
	private Integer traceId;
	private byte[] bdata;
	private String data1;
	private String data2;
	private Float rate;

	public Images() {
	}

	public Images(Euser euser, Locations locations, String imageSrc, Integer imageOwner, String demo, Integer traceId,
			byte[] bdata, String data1, String data2, Float rate) {
		this.euser = euser;
		this.locations = locations;
		this.imageSrc = imageSrc;
		this.imageOwner = imageOwner;
		this.demo = demo;
		this.traceId = traceId;
		this.bdata = bdata;
		this.data1 = data1;
		this.data2 = data2;
		this.rate = rate;
	}

	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	public Euser getEuser() {
		return this.euser;
	}

	public void setEuser(Euser euser) {
		this.euser = euser;
	}

	public Locations getLocations() {
		return this.locations;
	}

	public void setLocations(Locations locations) {
		this.locations = locations;
	}

	public String getImageSrc() {
		return this.imageSrc;
	}

	public void setImageSrc(String imageSrc) {
		this.imageSrc = imageSrc;
	}

	public Integer getImageOwner() {
		return this.imageOwner;
	}

	public void setImageOwner(Integer imageOwner) {
		this.imageOwner = imageOwner;
	}

	public String getDemo() {
		return this.demo;
	}

	public void setDemo(String demo) {
		this.demo = demo;
	}

	public Integer getTraceId() {
		return this.traceId;
	}

	public void setTraceId(Integer traceId) {
		this.traceId = traceId;
	}

	public byte[] getBdata() {
		return this.bdata;
	}

	public void setBdata(byte[] bdata) {
		this.bdata = bdata;
	}

	public String getData1() {
		return this.data1;
	}

	public void setData1(String data1) {
		this.data1 = data1;
	}

	public String getData2() {
		return this.data2;
	}

	public void setData2(String data2) {
		this.data2 = data2;
	}

	public Float getRate() {
		return this.rate;
	}

	public void setRate(Float rate) {
		this.rate = rate;
	}

}
