package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

import java.util.Date;

/**
 * Information generated by hbm2java
 */
public class Information implements java.io.Serializable {

	private Integer idinformation;
	private Euser euserByFromId;
	private Euser euserByToId;
	private Manager manager;
	private String content;
	private Integer readed;
	private Date genTime;
	private Integer inforType;

	public Information() {
	}

	public Information(Euser euserByFromId, Euser euserByToId, Manager manager, String content, Integer readed,
			Date genTime, Integer inforType) {
		this.euserByFromId = euserByFromId;
		this.euserByToId = euserByToId;
		this.manager = manager;
		this.content = content;
		this.readed = readed;
		this.genTime = genTime;
		this.inforType = inforType;
	}

	public Integer getIdinformation() {
		return this.idinformation;
	}

	public void setIdinformation(Integer idinformation) {
		this.idinformation = idinformation;
	}

	public Euser getEuserByFromId() {
		return this.euserByFromId;
	}

	public void setEuserByFromId(Euser euserByFromId) {
		this.euserByFromId = euserByFromId;
	}

	public Euser getEuserByToId() {
		return this.euserByToId;
	}

	public void setEuserByToId(Euser euserByToId) {
		this.euserByToId = euserByToId;
	}

	public Manager getManager() {
		return this.manager;
	}

	public void setManager(Manager manager) {
		this.manager = manager;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getReaded() {
		return this.readed;
	}

	public void setReaded(Integer readed) {
		this.readed = readed;
	}

	public Date getGenTime() {
		return this.genTime;
	}

	public void setGenTime(Date genTime) {
		this.genTime = genTime;
	}

	public Integer getInforType() {
		return this.inforType;
	}

	public void setInforType(Integer inforType) {
		this.inforType = inforType;
	}

}
