package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Locations generated by hbm2java
 */
public class Locations implements java.io.Serializable {

	private Integer idlocations;
	private Euser euser;
	private Traces traces;
	private String longitude;
	private String latitude;
	private String datetime;
	private String demo;
	private String data1;
	private String data2;
	private String lname;
	private Set imageses = new HashSet(0);

	public Locations() {
	}

	public Locations(String longitude, String latitude) {
		this.longitude = longitude;
		this.latitude = latitude;
	}

	public Locations(Euser euser, Traces traces, String longitude, String latitude, String datetime, String demo,
			String data1, String data2, String lname, Set imageses) {
		this.euser = euser;
		this.traces = traces;
		this.longitude = longitude;
		this.latitude = latitude;
		this.datetime = datetime;
		this.demo = demo;
		this.data1 = data1;
		this.data2 = data2;
		this.lname = lname;
		this.imageses = imageses;
	}

	public Integer getIdlocations() {
		return this.idlocations;
	}

	public void setIdlocations(Integer idlocations) {
		this.idlocations = idlocations;
	}

	public Euser getEuser() {
		return this.euser;
	}

	public void setEuser(Euser euser) {
		this.euser = euser;
	}

	public Traces getTraces() {
		return this.traces;
	}

	public void setTraces(Traces traces) {
		this.traces = traces;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getDatetime() {
		return this.datetime;
	}

	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}

	public String getDemo() {
		return this.demo;
	}

	public void setDemo(String demo) {
		this.demo = demo;
	}

	public String getData1() {
		return this.data1;
	}

	public void setData1(String data1) {
		this.data1 = data1;
	}

	public String getData2() {
		return this.data2;
	}

	public void setData2(String data2) {
		this.data2 = data2;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public Set getImageses() {
		return this.imageses;
	}

	public void setImageses(Set imageses) {
		this.imageses = imageses;
	}

}
