package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

import java.util.Date;

/**
 * Logm generated by hbm2java
 */
public class Logm implements java.io.Serializable {

	private Integer idLogM;
	private Manager manager;
	private Integer opType;
	private String content;
	private Date genTime;

	public Logm() {
	}

	public Logm(Manager manager) {
		this.manager = manager;
	}

	public Logm(Manager manager, Integer opType, String content, Date genTime) {
		this.manager = manager;
		this.opType = opType;
		this.content = content;
		this.genTime = genTime;
	}

	public Integer getIdLogM() {
		return this.idLogM;
	}

	public void setIdLogM(Integer idLogM) {
		this.idLogM = idLogM;
	}

	public Manager getManager() {
		return this.manager;
	}

	public void setManager(Manager manager) {
		this.manager = manager;
	}

	public Integer getOpType() {
		return this.opType;
	}

	public void setOpType(Integer opType) {
		this.opType = opType;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getGenTime() {
		return this.genTime;
	}

	public void setGenTime(Date genTime) {
		this.genTime = genTime;
	}

}
