package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * LongTwitter generated by hbm2java
 */
public class LongTwitter implements java.io.Serializable {

	private int idtwitterDemo;
	private Euser euser;
	private String blog;
	private String images;
	private Integer twitterId;
	private String title;

	public LongTwitter() {
	}

	public LongTwitter(int idtwitterDemo) {
		this.idtwitterDemo = idtwitterDemo;
	}

	public LongTwitter(int idtwitterDemo, Euser euser, String blog, String images, Integer twitterId, String title) {
		this.idtwitterDemo = idtwitterDemo;
		this.euser = euser;
		this.blog = blog;
		this.images = images;
		this.twitterId = twitterId;
		this.title = title;
	}

	public int getIdtwitterDemo() {
		return this.idtwitterDemo;
	}

	public void setIdtwitterDemo(int idtwitterDemo) {
		this.idtwitterDemo = idtwitterDemo;
	}

	public Euser getEuser() {
		return this.euser;
	}

	public void setEuser(Euser euser) {
		this.euser = euser;
	}

	public String getBlog() {
		return this.blog;
	}

	public void setBlog(String blog) {
		this.blog = blog;
	}

	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	public Integer getTwitterId() {
		return this.twitterId;
	}

	public void setTwitterId(Integer twitterId) {
		this.twitterId = twitterId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
