package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Manager generated by hbm2java
 */
public class Manager implements java.io.Serializable {

	private Integer idmanager;
	private Euser euser;
	private Organization organization;
	private Role role;
	private String username;
	private String email;
	private String pwdword;
	private String phone;
	private String qq;
	private String realname;
	private String UCode;
	private Date lastLogin;
	private Integer loginSum;
	private String createTime;
	private Integer gender;
	private Set logms = new HashSet(0);
	private Set informations = new HashSet(0);
	private Set newses = new HashSet(0);

	public Manager() {
	}

	public Manager(String email) {
		this.email = email;
	}

	public Manager(Euser euser, Organization organization, Role role, String username, String email, String pwdword,
			String phone, String qq, String realname, String UCode, Date lastLogin, Integer loginSum, String createTime,
			Integer gender, Set logms, Set informations, Set newses) {
		this.euser = euser;
		this.organization = organization;
		this.role = role;
		this.username = username;
		this.email = email;
		this.pwdword = pwdword;
		this.phone = phone;
		this.qq = qq;
		this.realname = realname;
		this.UCode = UCode;
		this.lastLogin = lastLogin;
		this.loginSum = loginSum;
		this.createTime = createTime;
		this.gender = gender;
		this.logms = logms;
		this.informations = informations;
		this.newses = newses;
	}

	public Integer getIdmanager() {
		return this.idmanager;
	}

	public void setIdmanager(Integer idmanager) {
		this.idmanager = idmanager;
	}

	public Euser getEuser() {
		return this.euser;
	}

	public void setEuser(Euser euser) {
		this.euser = euser;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPwdword() {
		return this.pwdword;
	}

	public void setPwdword(String pwdword) {
		this.pwdword = pwdword;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getUCode() {
		return this.UCode;
	}

	public void setUCode(String UCode) {
		this.UCode = UCode;
	}

	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	public Integer getLoginSum() {
		return this.loginSum;
	}

	public void setLoginSum(Integer loginSum) {
		this.loginSum = loginSum;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	public Set getLogms() {
		return this.logms;
	}

	public void setLogms(Set logms) {
		this.logms = logms;
	}

	public Set getInformations() {
		return this.informations;
	}

	public void setInformations(Set informations) {
		this.informations = informations;
	}

	public Set getNewses() {
		return this.newses;
	}

	public void setNewses(Set newses) {
		this.newses = newses;
	}

}
