package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * Media generated by hbm2java
 */
public class Media implements java.io.Serializable {

	private int mid;
	private Euser euser;
	private String url;
	private String filename;
	private String width;
	private String height;
	private Integer isShow;
	private byte[] data;

	public Media() {
	}

	public Media(int mid) {
		this.mid = mid;
	}

	public Media(int mid, Euser euser, String url, String filename, String width, String height, Integer isShow,
			byte[] data) {
		this.mid = mid;
		this.euser = euser;
		this.url = url;
		this.filename = filename;
		this.width = width;
		this.height = height;
		this.isShow = isShow;
		this.data = data;
	}

	public int getMid() {
		return this.mid;
	}

	public void setMid(int mid) {
		this.mid = mid;
	}

	public Euser getEuser() {
		return this.euser;
	}

	public void setEuser(Euser euser) {
		this.euser = euser;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getWidth() {
		return this.width;
	}

	public void setWidth(String width) {
		this.width = width;
	}

	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	public Integer getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Integer isShow) {
		this.isShow = isShow;
	}

	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

}
