package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private Integer mid;
	private Integer from;
	private Integer to;
	private String text;
	private Integer issystem;
	private Integer isread;
	private String sendtime;
	private String readtime;

	public Message() {
	}

	public Message(Integer from, Integer to, String text, Integer issystem, Integer isread, String sendtime,
			String readtime) {
		this.from = from;
		this.to = to;
		this.text = text;
		this.issystem = issystem;
		this.isread = isread;
		this.sendtime = sendtime;
		this.readtime = readtime;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public Integer getFrom() {
		return this.from;
	}

	public void setFrom(Integer from) {
		this.from = from;
	}

	public Integer getTo() {
		return this.to;
	}

	public void setTo(Integer to) {
		this.to = to;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Integer getIssystem() {
		return this.issystem;
	}

	public void setIssystem(Integer issystem) {
		this.issystem = issystem;
	}

	public Integer getIsread() {
		return this.isread;
	}

	public void setIsread(Integer isread) {
		this.isread = isread;
	}

	public String getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(String sendtime) {
		this.sendtime = sendtime;
	}

	public String getReadtime() {
		return this.readtime;
	}

	public void setReadtime(String readtime) {
		this.readtime = readtime;
	}

}
