package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * MusicSrc generated by hbm2java
 */
public class MusicSrc implements java.io.Serializable {

	private Integer musicSrcId;
	private Musics musics;
	private String src;

	public MusicSrc() {
	}

	public MusicSrc(Musics musics, String src) {
		this.musics = musics;
		this.src = src;
	}

	public Integer getMusicSrcId() {
		return this.musicSrcId;
	}

	public void setMusicSrcId(Integer musicSrcId) {
		this.musicSrcId = musicSrcId;
	}

	public Musics getMusics() {
		return this.musics;
	}

	public void setMusics(Musics musics) {
		this.musics = musics;
	}

	public String getSrc() {
		return this.src;
	}

	public void setSrc(String src) {
		this.src = src;
	}

}
