package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Musics generated by hbm2java
 */
public class Musics implements java.io.Serializable {

	private Integer musicId;
	private Albums albums;
	private String musicName;
	private String duration;
	private String src;
	private String lrcSrc;
	private Set musicSrcs = new HashSet(0);

	public Musics() {
	}

	public Musics(Albums albums, String musicName, String duration, String src, String lrcSrc, Set musicSrcs) {
		this.albums = albums;
		this.musicName = musicName;
		this.duration = duration;
		this.src = src;
		this.lrcSrc = lrcSrc;
		this.musicSrcs = musicSrcs;
	}

	public Integer getMusicId() {
		return this.musicId;
	}

	public void setMusicId(Integer musicId) {
		this.musicId = musicId;
	}

	public Albums getAlbums() {
		return this.albums;
	}

	public void setAlbums(Albums albums) {
		this.albums = albums;
	}

	public String getMusicName() {
		return this.musicName;
	}

	public void setMusicName(String musicName) {
		this.musicName = musicName;
	}

	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public String getSrc() {
		return this.src;
	}

	public void setSrc(String src) {
		this.src = src;
	}

	public String getLrcSrc() {
		return this.lrcSrc;
	}

	public void setLrcSrc(String lrcSrc) {
		this.lrcSrc = lrcSrc;
	}

	public Set getMusicSrcs() {
		return this.musicSrcs;
	}

	public void setMusicSrcs(Set musicSrcs) {
		this.musicSrcs = musicSrcs;
	}

}
