package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private Integer idnews;
	private Item item;
	private Manager manager;
	private String intro;
	private Date genTime;
	private String title;
	private String content;
	private Integer passcheked;
	private String keyword;
	private Integer defaultNews;
	private Integer clicked;
	private String newsUrl;
	private String imageUrl;
	private Integer commentSum;
	private Integer verify;
	private Integer verifyId;
	private Date verifyDate;
	private Set newsComments = new HashSet(0);

	public News() {
	}

	public News(Item item, Manager manager, String intro, Date genTime, String title, String content,
			Integer passcheked, String keyword, Integer defaultNews, Integer clicked, String newsUrl, String imageUrl,
			Integer commentSum, Integer verify, Integer verifyId, Date verifyDate, Set newsComments) {
		this.item = item;
		this.manager = manager;
		this.intro = intro;
		this.genTime = genTime;
		this.title = title;
		this.content = content;
		this.passcheked = passcheked;
		this.keyword = keyword;
		this.defaultNews = defaultNews;
		this.clicked = clicked;
		this.newsUrl = newsUrl;
		this.imageUrl = imageUrl;
		this.commentSum = commentSum;
		this.verify = verify;
		this.verifyId = verifyId;
		this.verifyDate = verifyDate;
		this.newsComments = newsComments;
	}

	public Integer getIdnews() {
		return this.idnews;
	}

	public void setIdnews(Integer idnews) {
		this.idnews = idnews;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Manager getManager() {
		return this.manager;
	}

	public void setManager(Manager manager) {
		this.manager = manager;
	}

	public String getIntro() {
		return this.intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

	public Date getGenTime() {
		return this.genTime;
	}

	public void setGenTime(Date genTime) {
		this.genTime = genTime;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getPasscheked() {
		return this.passcheked;
	}

	public void setPasscheked(Integer passcheked) {
		this.passcheked = passcheked;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public Integer getDefaultNews() {
		return this.defaultNews;
	}

	public void setDefaultNews(Integer defaultNews) {
		this.defaultNews = defaultNews;
	}

	public Integer getClicked() {
		return this.clicked;
	}

	public void setClicked(Integer clicked) {
		this.clicked = clicked;
	}

	public String getNewsUrl() {
		return this.newsUrl;
	}

	public void setNewsUrl(String newsUrl) {
		this.newsUrl = newsUrl;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public Integer getCommentSum() {
		return this.commentSum;
	}

	public void setCommentSum(Integer commentSum) {
		this.commentSum = commentSum;
	}

	public Integer getVerify() {
		return this.verify;
	}

	public void setVerify(Integer verify) {
		this.verify = verify;
	}

	public Integer getVerifyId() {
		return this.verifyId;
	}

	public void setVerifyId(Integer verifyId) {
		this.verifyId = verifyId;
	}

	public Date getVerifyDate() {
		return this.verifyDate;
	}

	public void setVerifyDate(Date verifyDate) {
		this.verifyDate = verifyDate;
	}

	public Set getNewsComments() {
		return this.newsComments;
	}

	public void setNewsComments(Set newsComments) {
		this.newsComments = newsComments;
	}

}
