package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

import java.util.Date;

/**
 * NewsComment generated by hbm2java
 */
public class NewsComment implements java.io.Serializable {

	private Integer idnewsComment;
	private Euser euser;
	private News news;
	private String commentName;
	private String email;
	private String content;
	private Date genTime;
	private Integer CType;

	public NewsComment() {
	}

	public NewsComment(Euser euser, News news, String commentName, String email, String content, Date genTime,
			Integer CType) {
		this.euser = euser;
		this.news = news;
		this.commentName = commentName;
		this.email = email;
		this.content = content;
		this.genTime = genTime;
		this.CType = CType;
	}

	public Integer getIdnewsComment() {
		return this.idnewsComment;
	}

	public void setIdnewsComment(Integer idnewsComment) {
		this.idnewsComment = idnewsComment;
	}

	public Euser getEuser() {
		return this.euser;
	}

	public void setEuser(Euser euser) {
		this.euser = euser;
	}

	public News getNews() {
		return this.news;
	}

	public void setNews(News news) {
		this.news = news;
	}

	public String getCommentName() {
		return this.commentName;
	}

	public void setCommentName(String commentName) {
		this.commentName = commentName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getGenTime() {
		return this.genTime;
	}

	public void setGenTime(Date genTime) {
		this.genTime = genTime;
	}

	public Integer getCType() {
		return this.CType;
	}

	public void setCType(Integer CType) {
		this.CType = CType;
	}

}
