package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Rights generated by hbm2java
 */
public class Rights implements java.io.Serializable {

	private Integer idRights;
	private Rights rights;
	private String name;
	private String url;
	private Set rightses = new HashSet(0);
	private Set rolerightreltions = new HashSet(0);

	public Rights() {
	}

	public Rights(Rights rights, String name, String url, Set rightses, Set rolerightreltions) {
		this.rights = rights;
		this.name = name;
		this.url = url;
		this.rightses = rightses;
		this.rolerightreltions = rolerightreltions;
	}

	public Integer getIdRights() {
		return this.idRights;
	}

	public void setIdRights(Integer idRights) {
		this.idRights = idRights;
	}

	public Rights getRights() {
		return this.rights;
	}

	public void setRights(Rights rights) {
		this.rights = rights;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Set getRightses() {
		return this.rightses;
	}

	public void setRightses(Set rightses) {
		this.rightses = rightses;
	}

	public Set getRolerightreltions() {
		return this.rolerightreltions;
	}

	public void setRolerightreltions(Set rolerightreltions) {
		this.rolerightreltions = rolerightreltions;
	}

}
