package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * Rolerightreltion generated by hbm2java
 */
public class Rolerightreltion implements java.io.Serializable {

	private int idRoleRightReltion;
	private Rights rights;
	private Role role;
	private int rightType;

	public Rolerightreltion() {
	}

	public Rolerightreltion(int idRoleRightReltion, Rights rights, Role role, int rightType) {
		this.idRoleRightReltion = idRoleRightReltion;
		this.rights = rights;
		this.role = role;
		this.rightType = rightType;
	}

	public int getIdRoleRightReltion() {
		return this.idRoleRightReltion;
	}

	public void setIdRoleRightReltion(int idRoleRightReltion) {
		this.idRoleRightReltion = idRoleRightReltion;
	}

	public Rights getRights() {
		return this.rights;
	}

	public void setRights(Rights rights) {
		this.rights = rights;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public int getRightType() {
		return this.rightType;
	}

	public void setRightType(int rightType) {
		this.rightType = rightType;
	}

}
