package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * TagRelation generated by hbm2java
 */
public class TagRelation implements java.io.Serializable {

	private TagRelationId id;

	public TagRelation() {
	}

	public TagRelation(TagRelationId id) {
		this.id = id;
	}

	public TagRelationId getId() {
		return this.id;
	}

	public void setId(TagRelationId id) {
		this.id = id;
	}

}
