package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * Tags generated by hbm2java
 */
public class Tags implements java.io.Serializable {

	private Integer tagid;
	private String tag;
	private String description;
	private String addUid;
	private String addtime;

	public Tags() {
	}

	public Tags(String tag, String description, String addUid, String addtime) {
		this.tag = tag;
		this.description = description;
		this.addUid = addUid;
		this.addtime = addtime;
	}

	public Integer getTagid() {
		return this.tagid;
	}

	public void setTagid(Integer tagid) {
		this.tagid = tagid;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAddUid() {
		return this.addUid;
	}

	public void setAddUid(String addUid) {
		this.addUid = addUid;
	}

	public String getAddtime() {
		return this.addtime;
	}

	public void setAddtime(String addtime) {
		this.addtime = addtime;
	}

}
