package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * Template generated by hbm2java
 */
public class Template implements java.io.Serializable {

	private Integer idtemplate;
	private String name;
	private String content;

	public Template() {
	}

	public Template(String name, String content) {
		this.name = name;
		this.content = content;
	}

	public Integer getIdtemplate() {
		return this.idtemplate;
	}

	public void setIdtemplate(Integer idtemplate) {
		this.idtemplate = idtemplate;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
