package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Traces generated by hbm2java
 */
public class Traces implements java.io.Serializable {

	private Integer idtraces;
	private Euser euser;
	private String traceName;
	private String buildTime;
	private String endTime;
	private String demo;
	private String data1;
	private String data2;
	private Set locationses = new HashSet(0);

	public Traces() {
	}

	public Traces(String traceName) {
		this.traceName = traceName;
	}

	public Traces(Euser euser, String traceName, String buildTime, String endTime, String demo, String data1,
			String data2, Set locationses) {
		this.euser = euser;
		this.traceName = traceName;
		this.buildTime = buildTime;
		this.endTime = endTime;
		this.demo = demo;
		this.data1 = data1;
		this.data2 = data2;
		this.locationses = locationses;
	}

	public Integer getIdtraces() {
		return this.idtraces;
	}

	public void setIdtraces(Integer idtraces) {
		this.idtraces = idtraces;
	}

	public Euser getEuser() {
		return this.euser;
	}

	public void setEuser(Euser euser) {
		this.euser = euser;
	}

	public String getTraceName() {
		return this.traceName;
	}

	public void setTraceName(String traceName) {
		this.traceName = traceName;
	}

	public String getBuildTime() {
		return this.buildTime;
	}

	public void setBuildTime(String buildTime) {
		this.buildTime = buildTime;
	}

	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getDemo() {
		return this.demo;
	}

	public void setDemo(String demo) {
		this.demo = demo;
	}

	public String getData1() {
		return this.data1;
	}

	public void setData1(String data1) {
		this.data1 = data1;
	}

	public String getData2() {
		return this.data2;
	}

	public void setData2(String data2) {
		this.data2 = data2;
	}

	public Set getLocationses() {
		return this.locationses;
	}

	public void setLocationses(Set locationses) {
		this.locationses = locationses;
	}

}
