package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

import java.util.Date;

/**
 * TwitterLove generated by hbm2java
 */
public class TwitterLove implements java.io.Serializable {

	private int idtwitterLove;
	private Euser euser;
	private Twitter twitter;
	private String content;
	private Date genTime;

	public TwitterLove() {
	}

	public TwitterLove(int idtwitterLove, Euser euser, Twitter twitter) {
		this.idtwitterLove = idtwitterLove;
		this.euser = euser;
		this.twitter = twitter;
	}

	public TwitterLove(int idtwitterLove, Euser euser, Twitter twitter, String content, Date genTime) {
		this.idtwitterLove = idtwitterLove;
		this.euser = euser;
		this.twitter = twitter;
		this.content = content;
		this.genTime = genTime;
	}

	public int getIdtwitterLove() {
		return this.idtwitterLove;
	}

	public void setIdtwitterLove(int idtwitterLove) {
		this.idtwitterLove = idtwitterLove;
	}

	public Euser getEuser() {
		return this.euser;
	}

	public void setEuser(Euser euser) {
		this.euser = euser;
	}

	public Twitter getTwitter() {
		return this.twitter;
	}

	public void setTwitter(Twitter twitter) {
		this.twitter = twitter;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getGenTime() {
		return this.genTime;
	}

	public void setGenTime(Date genTime) {
		this.genTime = genTime;
	}

}
