package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

import java.util.Date;

/**
 * TwitterComment generated by hbm2java
 */
public class TwitterComment implements java.io.Serializable {

	private Integer idtwitterComment;
	private Euser euser;
	private Twitter twitter;
	private String comment;
	private Date genTime;

	public TwitterComment() {
	}

	public TwitterComment(Twitter twitter, String comment) {
		this.twitter = twitter;
		this.comment = comment;
	}

	public TwitterComment(Euser euser, Twitter twitter, String comment, Date genTime) {
		this.euser = euser;
		this.twitter = twitter;
		this.comment = comment;
		this.genTime = genTime;
	}

	public Integer getIdtwitterComment() {
		return this.idtwitterComment;
	}

	public void setIdtwitterComment(Integer idtwitterComment) {
		this.idtwitterComment = idtwitterComment;
	}

	public Euser getEuser() {
		return this.euser;
	}

	public void setEuser(Euser euser) {
		this.euser = euser;
	}

	public Twitter getTwitter() {
		return this.twitter;
	}

	public void setTwitter(Twitter twitter) {
		this.twitter = twitter;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getGenTime() {
		return this.genTime;
	}

	public void setGenTime(Date genTime) {
		this.genTime = genTime;
	}

}
