package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * TwitterMedia generated by hbm2java
 */
public class TwitterMedia implements java.io.Serializable {

	private TwitterMediaId id;

	public TwitterMedia() {
	}

	public TwitterMedia(TwitterMediaId id) {
		this.id = id;
	}

	public TwitterMediaId getId() {
		return this.id;
	}

	public void setId(TwitterMediaId id) {
		this.id = id;
	}

}
