package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * TwitterMediaId generated by hbm2java
 */
public class TwitterMediaId implements java.io.Serializable {

	private Integer twitterid;
	private Integer mediaid;
	private Integer mid;

	public TwitterMediaId() {
	}

	public TwitterMediaId(Integer twitterid, Integer mediaid, Integer mid) {
		this.twitterid = twitterid;
		this.mediaid = mediaid;
		this.mid = mid;
	}

	public Integer getTwitterid() {
		return this.twitterid;
	}

	public void setTwitterid(Integer twitterid) {
		this.twitterid = twitterid;
	}

	public Integer getMediaid() {
		return this.mediaid;
	}

	public void setMediaid(Integer mediaid) {
		this.mediaid = mediaid;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TwitterMediaId))
			return false;
		TwitterMediaId castOther = (TwitterMediaId) other;

		return ((this.getTwitterid() == castOther.getTwitterid()) || (this.getTwitterid() != null
				&& castOther.getTwitterid() != null && this.getTwitterid().equals(castOther.getTwitterid())))
				&& ((this.getMediaid() == castOther.getMediaid()) || (this.getMediaid() != null
						&& castOther.getMediaid() != null && this.getMediaid().equals(castOther.getMediaid())))
				&& ((this.getMid() == castOther.getMid()) || (this.getMid() != null && castOther.getMid() != null
						&& this.getMid().equals(castOther.getMid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTwitterid() == null ? 0 : this.getTwitterid().hashCode());
		result = 37 * result + (getMediaid() == null ? 0 : this.getMediaid().hashCode());
		result = 37 * result + (getMid() == null ? 0 : this.getMid().hashCode());
		return result;
	}

}
