package com.jxust.svsh.entity;
// Generated 2017-4-11 10:04:36 by Hibernate Tools 5.1.2.Final

/**
 * Webshare generated by hbm2java
 */
public class Webshare implements java.io.Serializable {

	private Integer idwebshare;
	private Integer uid;
	private String description;
	private String header;
	private String url;
	private Integer ishow;

	public Webshare() {
	}

	public Webshare(Integer uid, String description, String header, String url, Integer ishow) {
		this.uid = uid;
		this.description = description;
		this.header = header;
		this.url = url;
		this.ishow = ishow;
	}

	public Integer getIdwebshare() {
		return this.idwebshare;
	}

	public void setIdwebshare(Integer idwebshare) {
		this.idwebshare = idwebshare;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getHeader() {
		return this.header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getIshow() {
		return this.ishow;
	}

	public void setIshow(Integer ishow) {
		this.ishow = ishow;
	}

}
